#ifndef __MEASUREMENT_H__
#define __MEASUREMENT_H__

#define SAMPLES_AMOUNT_PER_ONE_PERIOD 128U
#define AMOUNT_OF_PERIODS 3U
#define AMOUNT_OF_MEASUREMENT_CHANNELS 3U
#define AMOUNT_OF_ALL_SAMPLES SAMPLES_AMOUNT_PER_ONE_PERIOD * AMOUNT_OF_PERIODS * AMOUNT_OF_MEASUREMENT_CHANNELS

typedef uint32_t Sample_t;

extern Sample_t Samples[SAMPLES_AMOUNT_PER_ONE_PERIOD * AMOUNT_OF_PERIODS][AMOUNT_OF_MEASUREMENT_CHANNELS];



#endif